package cn.enn.bigdata.dataanalysis.model.local;

public class CalcCodeRelation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calc_code_relation.id
     *
     * @mbg.generated Thu Aug 29 09:49:45 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calc_code_relation.pid
     *
     * @mbg.generated Thu Aug 29 09:49:45 CST 2019
     */
    private Long pid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calc_code_relation.id
     *
     * @return the value of calc_code_relation.id
     *
     * @mbg.generated Thu Aug 29 09:49:45 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calc_code_relation.id
     *
     * @param id the value for calc_code_relation.id
     *
     * @mbg.generated Thu Aug 29 09:49:45 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calc_code_relation.pid
     *
     * @return the value of calc_code_relation.pid
     *
     * @mbg.generated Thu Aug 29 09:49:45 CST 2019
     */
    public Long getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calc_code_relation.pid
     *
     * @param pid the value for calc_code_relation.pid
     *
     * @mbg.generated Thu Aug 29 09:49:45 CST 2019
     */
    public void setPid(Long pid) {
        this.pid = pid;
    }
}