package cn.enn.bigdata.dataanalysis.model.local;

import java.math.BigDecimal;

public class Price {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column price.id
     *
     * @mbg.generated Thu Dec 05 17:04:27 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column price.price
     *
     * @mbg.generated Thu Dec 05 17:04:27 CST 2019
     */
    private BigDecimal price;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price.id
     *
     * @return the value of price.id
     * @mbg.generated Thu Dec 05 17:04:27 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price.id
     *
     * @param id the value for price.id
     * @mbg.generated Thu Dec 05 17:04:27 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price.price
     *
     * @return the value of price.price
     * @mbg.generated Thu Dec 05 17:04:27 CST 2019
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price.price
     *
     * @param price the value for price.price
     * @mbg.generated Thu Dec 05 17:04:27 CST 2019
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }
}