package cn.enn.bigdata.dataanalysis.dao.exchange;

import cn.enn.bigdata.dataanalysis.model.exchange.DealInfo;
import cn.enn.bigdata.dataanalysis.model.exchange.DealInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface DealInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deal_info
     *
     * @mbg.generated Tue Dec 17 15:21:54 CST 2019
     */
    long countByExample(DealInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deal_info
     *
     * @mbg.generated Tue Dec 17 15:21:54 CST 2019
     */
    int deleteByExample(DealInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deal_info
     *
     * @mbg.generated Tue Dec 17 15:21:54 CST 2019
     */
    @Delete({
        "delete from deal_info",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deal_info
     *
     * @mbg.generated Tue Dec 17 15:21:54 CST 2019
     */
    @Insert({
        "insert into deal_info (code, stock_id, ",
        "biz_time, buyer_id, ",
        "seller_id, count, price)",
        "values (#{code,jdbcType=VARCHAR}, #{stockId,jdbcType=BIGINT}, ",
        "#{bizTime,jdbcType=TIMESTAMP}, #{buyerId,jdbcType=BIGINT}, ",
        "#{sellerId,jdbcType=BIGINT}, #{count,jdbcType=BIGINT}, #{price,jdbcType=DECIMAL})"
    })
    @Options(useGeneratedKeys=true,keyProperty="id")
    int insert(DealInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deal_info
     *
     * @mbg.generated Tue Dec 17 15:21:54 CST 2019
     */
    int insertSelective(DealInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deal_info
     *
     * @mbg.generated Tue Dec 17 15:21:54 CST 2019
     */
    List<DealInfo> selectByExample(DealInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deal_info
     *
     * @mbg.generated Tue Dec 17 15:21:54 CST 2019
     */
    @Select({
        "select",
        "id, code, stock_id, biz_time, buyer_id, seller_id, count, price",
        "from deal_info",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("cn.enn.bigdata.dataanalysis.dao.exchange.DealInfoMapper.BaseResultMap")
    DealInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deal_info
     *
     * @mbg.generated Tue Dec 17 15:21:54 CST 2019
     */
    int updateByExampleSelective(@Param("record") DealInfo record, @Param("example") DealInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deal_info
     *
     * @mbg.generated Tue Dec 17 15:21:54 CST 2019
     */
    int updateByExample(@Param("record") DealInfo record, @Param("example") DealInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deal_info
     *
     * @mbg.generated Tue Dec 17 15:21:54 CST 2019
     */
    int updateByPrimaryKeySelective(DealInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deal_info
     *
     * @mbg.generated Tue Dec 17 15:21:54 CST 2019
     */
    @Update({
        "update deal_info",
        "set code = #{code,jdbcType=VARCHAR},",
          "stock_id = #{stockId,jdbcType=BIGINT},",
          "biz_time = #{bizTime,jdbcType=TIMESTAMP},",
          "buyer_id = #{buyerId,jdbcType=BIGINT},",
          "seller_id = #{sellerId,jdbcType=BIGINT},",
          "count = #{count,jdbcType=BIGINT},",
          "price = #{price,jdbcType=DECIMAL}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(DealInfo record);
}