package cn.wp.bigdata.dataanalysis.model.exchange;

import java.math.BigDecimal;
import java.util.Date;

public class DealInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deal_info.id
     *
     * @mbg.generated Tue Dec 17 15:21:54 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deal_info.code
     *
     * @mbg.generated Tue Dec 17 15:21:54 CST 2019
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deal_info.stock_id
     *
     * @mbg.generated Tue Dec 17 15:21:54 CST 2019
     */
    private Long stockId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deal_info.biz_time
     *
     * @mbg.generated Tue Dec 17 15:21:54 CST 2019
     */
    private Date bizTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deal_info.buyer_id
     *
     * @mbg.generated Tue Dec 17 15:21:54 CST 2019
     */
    private Long buyerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deal_info.seller_id
     *
     * @mbg.generated Tue Dec 17 15:21:54 CST 2019
     */
    private Long sellerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deal_info.count
     *
     * @mbg.generated Tue Dec 17 15:21:54 CST 2019
     */
    private Long count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deal_info.price
     *
     * @mbg.generated Tue Dec 17 15:21:54 CST 2019
     */
    private BigDecimal price;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deal_info.id
     *
     * @return the value of deal_info.id
     *
     * @mbg.generated Tue Dec 17 15:21:54 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deal_info.id
     *
     * @param id the value for deal_info.id
     *
     * @mbg.generated Tue Dec 17 15:21:54 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deal_info.code
     *
     * @return the value of deal_info.code
     *
     * @mbg.generated Tue Dec 17 15:21:54 CST 2019
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deal_info.code
     *
     * @param code the value for deal_info.code
     *
     * @mbg.generated Tue Dec 17 15:21:54 CST 2019
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deal_info.stock_id
     *
     * @return the value of deal_info.stock_id
     *
     * @mbg.generated Tue Dec 17 15:21:54 CST 2019
     */
    public Long getStockId() {
        return stockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deal_info.stock_id
     *
     * @param stockId the value for deal_info.stock_id
     *
     * @mbg.generated Tue Dec 17 15:21:54 CST 2019
     */
    public void setStockId(Long stockId) {
        this.stockId = stockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deal_info.biz_time
     *
     * @return the value of deal_info.biz_time
     *
     * @mbg.generated Tue Dec 17 15:21:54 CST 2019
     */
    public Date getBizTime() {
        return bizTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deal_info.biz_time
     *
     * @param bizTime the value for deal_info.biz_time
     *
     * @mbg.generated Tue Dec 17 15:21:54 CST 2019
     */
    public void setBizTime(Date bizTime) {
        this.bizTime = bizTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deal_info.buyer_id
     *
     * @return the value of deal_info.buyer_id
     *
     * @mbg.generated Tue Dec 17 15:21:54 CST 2019
     */
    public Long getBuyerId() {
        return buyerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deal_info.buyer_id
     *
     * @param buyerId the value for deal_info.buyer_id
     *
     * @mbg.generated Tue Dec 17 15:21:54 CST 2019
     */
    public void setBuyerId(Long buyerId) {
        this.buyerId = buyerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deal_info.seller_id
     *
     * @return the value of deal_info.seller_id
     *
     * @mbg.generated Tue Dec 17 15:21:54 CST 2019
     */
    public Long getSellerId() {
        return sellerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deal_info.seller_id
     *
     * @param sellerId the value for deal_info.seller_id
     *
     * @mbg.generated Tue Dec 17 15:21:54 CST 2019
     */
    public void setSellerId(Long sellerId) {
        this.sellerId = sellerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deal_info.count
     *
     * @return the value of deal_info.count
     *
     * @mbg.generated Tue Dec 17 15:21:54 CST 2019
     */
    public Long getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deal_info.count
     *
     * @param count the value for deal_info.count
     *
     * @mbg.generated Tue Dec 17 15:21:54 CST 2019
     */
    public void setCount(Long count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deal_info.price
     *
     * @return the value of deal_info.price
     *
     * @mbg.generated Tue Dec 17 15:21:54 CST 2019
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deal_info.price
     *
     * @param price the value for deal_info.price
     *
     * @mbg.generated Tue Dec 17 15:21:54 CST 2019
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }
}