package cn.wp.bigdata.dataanalysis.model.exchange;

public class StockInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_info.id
     *
     * @mbg.generated Tue Dec 17 15:21:54 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_info.code
     *
     * @mbg.generated Tue Dec 17 15:21:54 CST 2019
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_info.name
     *
     * @mbg.generated Tue Dec 17 15:21:54 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_info.des
     *
     * @mbg.generated Tue Dec 17 15:21:54 CST 2019
     */
    private String des;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_info.is_del
     *
     * @mbg.generated Tue Dec 17 15:21:54 CST 2019
     */
    private String isDel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_info.id
     *
     * @return the value of stock_info.id
     *
     * @mbg.generated Tue Dec 17 15:21:54 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_info.id
     *
     * @param id the value for stock_info.id
     *
     * @mbg.generated Tue Dec 17 15:21:54 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_info.code
     *
     * @return the value of stock_info.code
     *
     * @mbg.generated Tue Dec 17 15:21:54 CST 2019
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_info.code
     *
     * @param code the value for stock_info.code
     *
     * @mbg.generated Tue Dec 17 15:21:54 CST 2019
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_info.name
     *
     * @return the value of stock_info.name
     *
     * @mbg.generated Tue Dec 17 15:21:54 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_info.name
     *
     * @param name the value for stock_info.name
     *
     * @mbg.generated Tue Dec 17 15:21:54 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_info.des
     *
     * @return the value of stock_info.des
     *
     * @mbg.generated Tue Dec 17 15:21:54 CST 2019
     */
    public String getDes() {
        return des;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_info.des
     *
     * @param des the value for stock_info.des
     *
     * @mbg.generated Tue Dec 17 15:21:54 CST 2019
     */
    public void setDes(String des) {
        this.des = des == null ? null : des.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_info.is_del
     *
     * @return the value of stock_info.is_del
     *
     * @mbg.generated Tue Dec 17 15:21:54 CST 2019
     */
    public String getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_info.is_del
     *
     * @param isDel the value for stock_info.is_del
     *
     * @mbg.generated Tue Dec 17 15:21:54 CST 2019
     */
    public void setIsDel(String isDel) {
        this.isDel = isDel == null ? null : isDel.trim();
    }
}