package cn.enn.bigdata.dataanalysis.model.exchange;

import java.math.BigDecimal;
import java.util.Date;

public class OperInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oper_info.id
     *
     * @mbg.generated Tue Dec 17 15:21:54 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oper_info.stock_id
     *
     * @mbg.generated Tue Dec 17 15:21:54 CST 2019
     */
    private Long stockId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oper_info.oper_user
     *
     * @mbg.generated Tue Dec 17 15:21:54 CST 2019
     */
    private Long operUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oper_info.oper_type
     *
     * @mbg.generated Tue Dec 17 15:21:54 CST 2019
     */
    private String operType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oper_info.count
     *
     * @mbg.generated Tue Dec 17 15:21:54 CST 2019
     */
    private Long count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oper_info.price
     *
     * @mbg.generated Tue Dec 17 15:21:54 CST 2019
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oper_info.biz_time
     *
     * @mbg.generated Tue Dec 17 15:21:54 CST 2019
     */
    private Date bizTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oper_info.id
     *
     * @return the value of oper_info.id
     *
     * @mbg.generated Tue Dec 17 15:21:54 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oper_info.id
     *
     * @param id the value for oper_info.id
     *
     * @mbg.generated Tue Dec 17 15:21:54 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oper_info.stock_id
     *
     * @return the value of oper_info.stock_id
     *
     * @mbg.generated Tue Dec 17 15:21:54 CST 2019
     */
    public Long getStockId() {
        return stockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oper_info.stock_id
     *
     * @param stockId the value for oper_info.stock_id
     *
     * @mbg.generated Tue Dec 17 15:21:54 CST 2019
     */
    public void setStockId(Long stockId) {
        this.stockId = stockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oper_info.oper_user
     *
     * @return the value of oper_info.oper_user
     *
     * @mbg.generated Tue Dec 17 15:21:54 CST 2019
     */
    public Long getOperUser() {
        return operUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oper_info.oper_user
     *
     * @param operUser the value for oper_info.oper_user
     *
     * @mbg.generated Tue Dec 17 15:21:54 CST 2019
     */
    public void setOperUser(Long operUser) {
        this.operUser = operUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oper_info.oper_type
     *
     * @return the value of oper_info.oper_type
     *
     * @mbg.generated Tue Dec 17 15:21:54 CST 2019
     */
    public String getOperType() {
        return operType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oper_info.oper_type
     *
     * @param operType the value for oper_info.oper_type
     *
     * @mbg.generated Tue Dec 17 15:21:54 CST 2019
     */
    public void setOperType(String operType) {
        this.operType = operType == null ? null : operType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oper_info.count
     *
     * @return the value of oper_info.count
     *
     * @mbg.generated Tue Dec 17 15:21:54 CST 2019
     */
    public Long getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oper_info.count
     *
     * @param count the value for oper_info.count
     *
     * @mbg.generated Tue Dec 17 15:21:54 CST 2019
     */
    public void setCount(Long count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oper_info.price
     *
     * @return the value of oper_info.price
     *
     * @mbg.generated Tue Dec 17 15:21:54 CST 2019
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oper_info.price
     *
     * @param price the value for oper_info.price
     *
     * @mbg.generated Tue Dec 17 15:21:54 CST 2019
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oper_info.biz_time
     *
     * @return the value of oper_info.biz_time
     *
     * @mbg.generated Tue Dec 17 15:21:54 CST 2019
     */
    public Date getBizTime() {
        return bizTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oper_info.biz_time
     *
     * @param bizTime the value for oper_info.biz_time
     *
     * @mbg.generated Tue Dec 17 15:21:54 CST 2019
     */
    public void setBizTime(Date bizTime) {
        this.bizTime = bizTime;
    }
}