package cn.enn.bigdata.dataanalysis.dao.local;

import cn.enn.bigdata.dataanalysis.model.local.CalcCodeRelation;
import cn.enn.bigdata.dataanalysis.model.local.CalcCodeRelationExample;

import java.util.List;

import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;

public interface CalcCodeRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calc_code_relation
     *
     * @mbg.generated Thu Aug 29 09:49:45 CST 2019
     */
    long countByExample(CalcCodeRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calc_code_relation
     *
     * @mbg.generated Thu Aug 29 09:49:45 CST 2019
     */
    int deleteByExample(CalcCodeRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calc_code_relation
     *
     * @mbg.generated Thu Aug 29 09:49:45 CST 2019
     */
    @Insert({
        "insert into calc_code_relation (pid)",
        "values (#{pid,jdbcType=BIGINT})"
    })
    @Options(useGeneratedKeys=true,keyProperty="id")
    int insert(CalcCodeRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calc_code_relation
     *
     * @mbg.generated Thu Aug 29 09:49:45 CST 2019
     */
    int insertSelective(CalcCodeRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calc_code_relation
     *
     * @mbg.generated Thu Aug 29 09:49:45 CST 2019
     */
    List<CalcCodeRelation> selectByExample(CalcCodeRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calc_code_relation
     *
     * @mbg.generated Thu Aug 29 09:49:45 CST 2019
     */
    int updateByExampleSelective(@Param("record") CalcCodeRelation record, @Param("example") CalcCodeRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calc_code_relation
     *
     * @mbg.generated Thu Aug 29 09:49:45 CST 2019
     */
    int updateByExample(@Param("record") CalcCodeRelation record, @Param("example") CalcCodeRelationExample example);
}