package cn.enn.bigdata.dataanalysis.dao.local;

import cn.enn.bigdata.dataanalysis.model.local.Price;
import cn.enn.bigdata.dataanalysis.model.local.PriceExample;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface PriceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table price
     *
     * @mbg.generated Thu Dec 05 17:04:27 CST 2019
     */
    long countByExample(PriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table price
     *
     * @mbg.generated Thu Dec 05 17:04:27 CST 2019
     */
    int deleteByExample(PriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table price
     *
     * @mbg.generated Thu Dec 05 17:04:27 CST 2019
     */
    @Delete({
        "delete from price",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table price
     *
     * @mbg.generated Thu Dec 05 17:04:27 CST 2019
     */
    @Insert({
        "insert into price (price)",
        "values (#{price,jdbcType=DECIMAL})"
    })
    @Options(useGeneratedKeys=true,keyProperty="id")
    int insert(Price record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table price
     *
     * @mbg.generated Thu Dec 05 17:04:27 CST 2019
     */
    int insertSelective(Price record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table price
     *
     * @mbg.generated Thu Dec 05 17:04:27 CST 2019
     */
    List<Price> selectByExample(PriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table price
     *
     * @mbg.generated Thu Dec 05 17:04:27 CST 2019
     */
    @Select({
        "select",
        "id, price",
        "from price",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("PriceMapper.BaseResultMap")
    Price selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table price
     *
     * @mbg.generated Thu Dec 05 17:04:27 CST 2019
     */
    int updateByExampleSelective(@Param("record") Price record, @Param("example") PriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table price
     *
     * @mbg.generated Thu Dec 05 17:04:27 CST 2019
     */
    int updateByExample(@Param("record") Price record, @Param("example") PriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table price
     *
     * @mbg.generated Thu Dec 05 17:04:27 CST 2019
     */
    int updateByPrimaryKeySelective(Price record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table price
     *
     * @mbg.generated Thu Dec 05 17:04:27 CST 2019
     */
    @Update({
        "update price",
        "set price = #{price,jdbcType=DECIMAL}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(Price record);
}